apiVersion: v1
kind: Secret
metadata:
  name: registry-pull-secret
data:
  .dockerconfigjson:  ewoJImF1dGhzIjogewoJCSIzNC45Ni4yMzcuNzgiOiB7CgkJCSJhdXRoIjogIllXUnRhVzQ2TVRJek5EVTJjM2RxIgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOC4wOS42IChsaW51eCkiCgl9Cn0=
type: kubernetes.io/dockerconfigjson
